### ISSUE TITLE
Missing pre-built package linux-aarch64 for python-3.9

### ISSUE THREAD

**Issue by mathbunnyru** [conda-forge/bottleneck-feedstock#35]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Missing pre-built package `linux-aarch64` for python-3.9.

The reason I'm asking:

We're trying to add support for ARM based docker images in https://github.com/jupyter/docker-stacks/issues/1019.
It would be great to have bottleneck supported.

**Comment by mathbunnyru** [comment]
https://anaconda.org/conda-forge/bottleneck/files

I can see `linux-64` is present for py39, so I think it should be fine for arm.

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/conda-forge/bottleneck-feedstock/pull/38 )
